# Generated by Django 5.0.7 on 2024-08-04 22:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="98846183", max_length=128, region="UY"
            ),
            preserve_default=False,
        ),
    ]
