# Generated by Django 5.0.7 on 2024-07-28 21:14

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='vendors/logos', verbose_name='Logo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('max_orders', models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Máximo de pedidos')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
            bases=('core.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('photo', models.ImageField(upload_to='menus/photos', verbose_name='Foto')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
        migrations.CreateModel(
            name='ExceptionalClosingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Día de cierre excepcional',
                'verbose_name_plural': 'Días de cierre excepcionales',
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='staff',
            field=models.ManyToManyField(to='vendors.vendoruser', verbose_name='Personal'),
        ),
        migrations.CreateModel(
            name='WeekendWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de cierre')),
                ('max_orders', models.PositiveIntegerField(default=10, verbose_name='Máximo de pedidos')),
                ('order_limit_time', models.TimeField(verbose_name='Hora límite para pedidos')),
                ('delivery_start_time', models.TimeField(verbose_name='Hora de inicio de entregas')),
                ('saturday', models.BooleanField(default=True, verbose_name='Sábado')),
                ('sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Horario de trabajo fin de semana',
                'verbose_name_plural': 'Horarios de trabajo fin de semana',
            },
        ),
        migrations.CreateModel(
            name='WeekWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(verbose_name='Hora de apertura')),
                ('closing_time', models.TimeField(verbose_name='Hora de cierre')),
                ('max_orders', models.PositiveIntegerField(default=10, verbose_name='Máximo de pedidos')),
                ('order_limit_time', models.TimeField(verbose_name='Hora límite para pedidos')),
                ('delivery_start_time', models.TimeField(verbose_name='Hora de inicio de entregas')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Horario de trabajo semanal',
                'verbose_name_plural': 'Horarios de trabajo semanales',
            },
        ),
    ]
