# Generated by Django 5.0.7 on 2024-08-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendoruser_selected_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendoruser',
            options={'verbose_name': 'Usuario proveedor', 'verbose_name_plural': 'Usuarios proveedores'},
        ),
    ]
