# Generated by Django 5.0.7 on 2024-08-05 01:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendoruser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='98846183', max_length=128, region='UY', verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='staff',
            field=models.ManyToManyField(related_name='vendors_managed', to='vendors.vendoruser', verbose_name='Personal'),
        ),
    ]
