# Generated by Django 5.0.7 on 2024-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_phone_alter_vendor_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(default='Pepe Santos 123', max_length=255, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='max_orders',
            field=models.PositiveIntegerField(blank=True, default=15, null=True, verbose_name='Máximo de pedidos'),
        ),
    ]
