# Generated by Django 5.0.7 on 2024-08-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_address_alter_vendor_max_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_owned', to='vendors.vendoruser'),
        ),
    ]
